# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "efc01a731b92895b3ffab3fc26492280"
name = "my-first-app"
handle = "my-first-app-854"
application_url = "https://bidder-betting-accountability-gcc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "apptesting-2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bidder-betting-accountability-gcc.trycloudflare.com/auth/callback",
  "https://bidder-betting-accountability-gcc.trycloudflare.com/auth/shopify/callback",
  "https://bidder-betting-accountability-gcc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
